apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: testing-wf 
spec:
  entrypoint: whalesay
  templates:
    - name: whalesay
      container:
        image: docker/whalesay
        command: [ cowsay ]
        args: [ "hello world" ]
        resources: # limit the resources
          limits:
            memory: 32Mi
            cpu: 120m
