apiVersion: argoproj.io/v1alpha1
kind: Workflow                  # new type of k8s spec
metadata:
  generateName: testing-wf-    # name of the workflow spec
spec:
  entrypoint: whalesay12          # invoke the whalesay template
  templates:
    - name: whalesay11              # name of the template
      container:
        image: docker/whalesay
        command: [ cowsay ]
        args: [ "hello world" ]
        resources: # limit the resources
          limits:
            memory: 32Mi
            cpu: 100m
